# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command, `snippet` to add a Zephyr snippet, and
# `artifact-name` to assign a name to distinguish build outputs from each other:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#   - board: nice_nano_v2
#     shield: corne_left
#     snippet: studio-rpc-usb-uart
#     cmake-args: -DCONFIG_ZMK_STUDIO=y
#     artifact-name: corne_left_with_studio
#
---
include:
  - board: ergokeeb_corne_left
    shield: nice_view
  - board: ergokeeb_corne_right
    shield: nice_view
  - board: ergokeeb_corne_left
    shield: nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: corne_studio_left
  - board: ergokeeb_corne_left
    shield: settings_reset
    #snippet: zmk-usb-logging

  # the following work via the github build process.
  # we need to move the ability to make it into our own build script
  - board: ergokeeb_corne_left
    shield: nice_view_adapter nice_view_gem
    artifact-name: ergokeeb_corne_left_gem
  - board: ergokeeb_corne_right
    shield: nice_view_adapter nice_view_gem
    artifact-name: ergokeeb_corne_right_gem
  