manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
    - name: m165437
      url-base: https://github.com/M165437
    - name: carrefinho
      url-base: https://github.com/carrefinho
    - name: pandakb
      url-base: https://github.com/PandaKBLab
    - name: urob
      url-base: https://github.com/urob
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: nice-view-gem
      remote: m165437
      revision: main
    - name: prospector-zmk-module
      remote: carrefinho
      revision: main
    - name: corne-j-keyboard-zmk
      remote: pandakb
      revision: main
#      import: config/west.yml
#    - name: zmk-leader-key
#      remote: urob
#      #revision: v0.2 # set to same as urob's patched ZMK version, and build against that if there are build errors as per urob' doc
  self:
    path: config
